version: '2'
services:
  docker-skeleton-php-nginx-app:
    stdin_open: true
    tty: true
    build:
        context: ./app
        dockerfile: Dockerfile
    volumes:
      - ../:/app
      - ./app/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    ports:
      - "80:80"
    environment:
      JWT_SECRET: password
      XDEBUG_CONFIG: "remote_host=${XDEBUG_HOST}"
      PHP_IDE_CONFIG: "serverName=${SERVICE_NAME}"
      ENVIRONMENT: development
    networks:
      - adrnet
networks:
  adrnet:
    driver: "bridge"